--- # EC2 volume creation and add
- hosts: localhost
  connection: local
  remote_user: test
  become: yes
  gather_facts: no
  tasks:
  - name: Create the volume
    ec2_vol:
      region: us-east-1
      instance: i-058a36866d9adceab
      volume_size: 1
      device_name: sdf
    register: volume_result
  - debug: msg={{ volume_result }}
