- name: Create dirs for config and certs holds
  shell: mkdir /tmp/{{ item }}
  with_items:
  - "{{ etcd0_host }}"
  - "{{ etcd1_host }}"
  - "{{ etcd2_host }}"

- name: Create configuration files for kubeadm etcd
  template: src=../templates/kubeadmcfg.yaml dest=/tmp/{{ item.name }} 
  with_items:
  - { ip: "{{ etcd0 }}", name: "{{ etcd0_host }}" }
  - { ip: "{{ etcd1 }}", name: "{{ etcd1_host }}" }
  - { ip: "{{ etcd2 }}", name: "{{ etcd2_host }}" }

- name: Create kube ssl directories
  shell: mkdir -pv /etc/kubernetes/pki/etcd

- name: Generate CA
  shell: kubeadm alpha phase certs etcd-ca

- name: Create certificates for each member
  shell: |
    kubeadm alpha phase certs etcd-server --config=/tmp/{{ item.name }}/kubeadmcfg.yaml 
    kubeadm alpha phase certs etcd-peer --config=/tmp/{{ item.name }}/kubeadmcfg.yaml 
    kubeadm alpha phase certs etcd-healthcheck-client --config=/tmp/{{ item.name }}/kubeadmcfg.yaml
    kubeadm alpha phase certs apiserver-etcd-client --config=/tmp/{{ item.name }}/kubeadmcfg.yaml 
    cp -R /etc/kubernetes/pki /tmp/{{ item.name }}/
    find /etc/kubernetes/pki -not -name ca.crt -not -name ca.key -type f -delete 
    chown -R ansible:ansible /tmp/{{ item.name }}
  with_items:
  - { ip: "{{ etcd0 }}", name: "{{ etcd0_host }}" }
  - { ip: "{{ etcd1 }}", name: "{{ etcd1_host }}" }
  - { ip: "{{ etcd2 }}", name: "{{ etcd2_host }}" }

- name: Archive files
  archive:
    path: /tmp/{{ item }}/
    dest: /tmp/{{ item }}.tgz
  with_items:
  - "{{ etcd0_host }}"
  - "{{ etcd1_host }}"
  - "{{ etcd2_host }}"

- name: Fetch certs for later use in kube bootstrap
  fetch:
    src: /tmp/{{ item }}.tgz
    dest: /tmp/{{ item }}.tgz
    flat: yes
  with_items:
  - "{{ etcd0_host }}"
  - "{{ etcd1_host }}"
  - "{{ etcd2_host }}"

- fetch: 
    src: /tmp/{{ etcd0_host }}/pki/apiserver-etcd-client.crt
    dest: /tmp/apiserver-etcd-client.crt
    flat: yes
- fetch:
    src: /tmp/{{ etcd0_host }}/pki/apiserver-etcd-client.key
    dest: /tmp/apiserver-etcd-client.key
    flat: yes
- fetch:
    src: /tmp/{{ etcd0_host }}/pki/etcd/ca.crt
    dest: /tmp/ca.crt
    flat: yes

- name: Clean up
  shell: rm /tmp/* -rf
