--- # ANsible tag example playbook
- hosts: aws
  remote_user: test
  become: yes
  gather_facts: no
  connection: ssh
  tasks:
  - name: install httpd
    yum: pkg={{ item }} state=latest
    with_items:
      - telnet
      - lynx
    tags:
      - packages
  - name: verify that telnet is installed
    raw: yum list installed | grep telnet > /home/test/package.log
    tags:
      - verification
