--- # Ansible waitfor module example
- hosts: aws
  remote_user: test
  become: yes
  connection: ssh
  gather_facts: yes
  tasks:
  - name: install httpd
    yum: pkg=httpd state=latest
  - name: wait for port 80 to listen
    wait_for:
      port: 80
      state: started
  - name: install lynx for example
    yum: name=lynx state=latest
