--- ## Hosts for kubernetes
- hosts: etcd
  remote_user: ansible
  become: yes
  connection: ssh
  gather_facts: yes
  tasks:
  - name: Copy hosts file to nodes
    copy: src=files/hosts dest=/etc/hosts owner=root group=root mode=0644
  - name: Copy k8s.conf to /etc/sysctl.d
    copy: src=files/k8s.conf dest=/etc/sysctl.d/k8s.conf owner=root group=root mode=0644
  - name: install docker deps
    yum: name=yum-utils state=latest
  - yum: name=device-mapper-persistent-data state=latest
  - yum: name=lvm2 state=latest
  - shell: yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
#  - shell: sudo yum install -y ftp://bo.mirror.garr.it/1/slc/centos/7.1.1503/extras/x86_64/Packages/container-selinux-2.9-4.el7.noarch.rpm
  - yum: name=docker-ce state=latest
  - service: name=docker state=restarted enabled=yes
  - name: kubernetes packages
    shell: yum-config-manager --add-repo https://packages.cloud.google.com/yum/repos/kubernetes-el7-x86_64
  - name: kubernetes install
    shell: yum install kubeadm kubectl kubelet -y --nogpgcheck
    tags:
    - kubernetes
  - service: name=kubelet state=restarted enabled=yes
