--- # ISCSI target setup
- hosts: storage
  remote_user: viktor
  become: yes
  connection: ssh
  gather_facts: yes
  vars_files:
    - vars/variables.yml
  tasks:
  - name: Install target packages
    yum: name=targetcli state=latest
  - name: Make target config
    shell: targetcli /backstores/block create drive {{ block_device }}
  - shell: targetcli /iscsi create {{ iqn_name }}:target
  - shell: targetcli /iscsi/{{ iqn_name }}:target/tpg1/luns create /backstores/block/drive
  - shell: targetcli /iscsi/{{ iqn_name }}:target/tpg1/acls create {{ iqn_name }}:client
  - shell: targetcli /iscsi/{{ iqn_name }}:target/tpg1/acls/{{ iqn_name }}:client set auth userid={{ iscsi_user }}
  - shell: targetcli /iscsi/{{ iqn_name }}:target/tpg1/acls/{{ iqn_name }}:client set auth password={{ iscsi_pass }} 
  - shell: targetcli saveconfig
  - service: name=target state=started enabled=yes
