--- # Install and set up kerberos
- hosts: kdc
  remote_user: viktor
  become: yes
  connection: ssh
  gather_facts: no
  vars_files:
    - vars/variables.yml
  tasks:
  - name: Install required packages
    yum: name=krb5-server state=latest
  - yum: name=krb5-workstation state=latest
  - yum: name=pam_krb5 state=latest
  - name: Copy required files
    template: src=files/kdc.conf dest=/var/kerberos/krb5kdc/kdc.conf owner=root group=root mode=644
  - template: src=files/kadm5.acl dest=/var/kerberos/krb5kdc/kadm5.acl owner=root group=root mode=644
  - template: src=files/krb5.conf  dest=/etc/krb5.conf owner=root group=root mode=644
  - name: Generate kerberos database
    shell: kdb5_util create -P {{ kdb_password }} -s -r {{ realm_caps }} 
  - name: Start and enable services
    service: name=krb5kdc state=started enabled=yes
  - service: name=kadmin state=started enabled=yes
  - name: Adding principals
    shell: kadmin.local -q "addprinc -pw {{ admin_pass }} root/admin"
  - shell: kadmin.local -q "addprinc -randkey host/{{ kdc_server }}"
  - shell: kadmin.local -q "ktadd host/{{ kdc_server }}"
  - shell: kadmin.local -q "addprinc -randkey {{ user_principle }}"
  - name: Modify and reload sshd
    copy: src=files/ssh_config dest=/etc/ssh/ssh_config owner=root group=root mode=640
  - shell: authconfig --enablekrb5 --update
  - service: name=sshd state=reloaded
