--- # krb clients setup
- hosts: storage
  remote_user: viktor
  become: yes
  connection: ssh
  gather_facts: yes
  vars_files:
    - vars/variables.yml
  tasks:
  - name: Install packages
    yum: name=krb5-workstation state=latest
  - yum: name=pam_krb5 state=latest
  - yum: name=policycoreutils-python-2.5-22.el7 state=latest
  - name: Copy config file
    template: src=files/krb5.conf dest=/etc/krb5.conf owner=root group=root mode=644
  - name: Add principals
    shell: kadmin -w {{ admin_pass }} -q "{{ item }}"
    with_items:
      - addprinc -randkey host/{{ nfs_server }}
      - ktadd host/{{ nfs_server }}
      - addprinc -randkey nfs/{{ nfs_server }}
      - ktadd nfs/{{ nfs_server }}
  - name: Install nfs package
    yum: name=nfs-utils state=latest
  - name: Create export dir
    file: 
      path: /export
      state: directory
      mode: 0777
    ignore_errors: yes
  - shell: semanage fcontext -at public_content_rw_t "/export(/.*)?"
  - shell: restorecon -Rv /export
  - name: Modify /etc/exports
    lineinfile: 
      path: /etc/exports 
      line: "/export {{ servers_network }}(rw,sync,no_root_squash,sec=krb5)"
  - service: name=rpcbind state=started enabled=yes
  - service: name=nfs-server state=started enabled=yes
  - shell: exportfs -arv


