- name: Install nfs server
  apt: name=nfs-kernel-server state=latest

- service: name=nfs-kernel-server state=stopped enabled=no

- name: Create nfs resource
  shell: |
    'crm configure primitive p_nfsserver ocf:heartbeat:nfsserver params nfs_shared_infodir=/kubernetes/nfs_shared_info nfs_ip={{ shared_ip }} op start interval=0s timeout=40s op stop interval=0s timeout=20s op monitor interval=10s timeout=20s'
    'crm configure order o_fs_drbd-before-nfsserver inf: p_fs_drbd p_nfsserver'
    'crm configure colocation c_nfsserver-with-fs_drbd inf: p_nfsserver p_fs_drbd'


