apiVersion: "kubeadm.k8s.io/v1alpha3"
kind: ClusterConfiguration
etcd:
  local:
    serverCertSANs:
    - "{{ item.ip }}"
    peerCertSANs:
    - "{{ item.ip }}"
    extraArgs:
      initial-cluster: {{ etcd0_host }}=https://{{ etcd0 }}:2380,{{ etcd1_host }}=https://{{ etcd1 }}:2380,{{ etcd2_host }}=https://{{ etcd2 }}:2380
      initial-cluster-state: new
      name: "{{ item.name }}"
      listen-peer-urls: https://{{ item.ip }}:2380
      listen-client-urls: https://{{ item.ip }}:2379
      advertise-client-urls: https://{{ item.ip }}:2379
      initial-advertise-peer-urls: https://{{ item.ip }}:2380
