##### Helm and tiller instal ######
- name: Install helm to the cluster
  shell: |
    wget https://storage.googleapis.com/kubernetes-helm/helm-v2.11.0-linux-amd64.tar.gz -P /root
    tar -xzf /root/helm-v2.11.0-linux-amd64.tar.gz -C /root
    cp /root/linux-amd64/helm /usr/bin
    rm /root/helm* -rf
    rm /root/linux-* -rf

- name: create post-install directory
  file:
    path: /root/post-install
    state: directory

- name: Copy tempalte for sa
  template: src=../templates/tiller-sa.yml dest=/root/post-install/tiller-sa.yml

- name: Create service account for tiller
  shell: kubectl create -f /root/post-install/tiller-sa.yml

- name: Install tiller to the cluster
  shell: helm init --service-account=tiller

- name: Wait for tiller to be ready
  pause: minutes=1

##### Install prometheus and grafana for cluster monitoring with helm ######

- name: prometheus and grafana for cluster monitoring with helm
  shell: |
    helm repo add coreos https://s3-eu-west-1.amazonaws.com/coreos-charts/stable/
    helm install coreos/prometheus-operator --name prometheus-operator --namespace monitoring
    helm install coreos/kube-prometheus --name kube-prometheus --set global.rbacEnable=true --namespace monitoring

##### Nginx ingress controller deploy #################

- name: Deploy ingress controller
  shell: |
    kubectl apply -f https://raw.githubusercontent.com/kubernetes/ingress-nginx/master/deploy/mandatory.yaml
    kubectl apply -f https://raw.githubusercontent.com/kubernetes/ingress-nginx/master/deploy/provider/baremetal/service-nodeport.yaml

##### Heketi install for glusterfs volumes provisioning ######
- name: Label master node for heketi
  shell: kubectl label node "{{ ansible_hostname }}" app=heketi

- name: Create heketi directories
  file:
    path: /var/lib/heketi
    state: directory
- file:
    path: /etc/heketi
    state: directory
    
- name: Create directory for post install tasks
  file:
    path: /root/post-install
    state: directory
    owner: root

- template: src=../templates/storage-class-template.yml dest=/root/post-install/storage-class-template.yml

- name: Create and run heketi container
  template: src=../templates/heketi.yml dest=/root/post-install/heketi.yml

- name: Run heketi
  shell: kubectl create -f /root/post-install/heketi.yml
  register: out
- debug: msg={{ out }}

###### Info ######

- debug: msg="Prometheus and grafana are now installed , in order to use grafana create ingress for the service or use kubectl port forward on port 3000"

- debug: msg="Heketi is now installed as deployment to kube-system namespace to finish the  installation Copy the pub key(/var/lib/heketi/.ssh/id_rsa.pub) to all worker nodes"

- debug: msg="Modify the topology file (/etc/heketi/topology.json) to reflect the correct workers and volumes , run heketi-cli topology load --json=/etc/heketi/topology.json"

- debug: msg="Create storage class (/root/post-install/storage-class-template.yml) can be used"
