- name: install ossec dependancies
  yum: pkg=gcc state=latest
- yum: pkg=bind-utils state=latest
- name: Download ossec package
  shell: wget -O /tmp/ossec.2.9.3.tar.gz https://github.com/ossec/ossec-hids/archive/2.9.3.tar.gz
- shell: tar -xzf /tmp/ossec.2.9.3.tar.gz -C /tmp
- copy:
    remote_src: yes
    src: /tmp/ossec-hids-2.9.3/etc/preloaded-vars.conf.example
    dest: /tmp/ossec-hids-2.9.3/etc/preloaded-vars.conf
- name: Change the values in preloaded-vars.conf to automate installation
  shell: sed -i 's/#USER_LANGUAGE="en"/USER_LANGUAGE="en"/' /tmp/ossec-hids-2.9.3/etc/preloaded-vars.conf
- shell: sed -i 's/#USER_INSTALL_TYPE="local"/USER_INSTALL_TYPE="local"/' /tmp/ossec-hids-2.9.3/etc/preloaded-vars.conf
- shell: sed -i 's/#USER_DIR="\/var\/ossec"/USER_DIR="\/var\/ossec"/' /tmp/ossec-hids-2.9.3/etc/preloaded-vars.conf
- shell: sed -i 's/#USER_ENABLE_ACTIVE_RESPONSE="y"/USER_ENABLE_ACTIVE_RESPONSE="y"/' /tmp/ossec-hids-2.9.3/etc/preloaded-vars.conf
- shell: sed -i 's/#USER_ENABLE_SYSCHECK="y"/USER_ENABLE_SYSCHECK="y"/' /tmp/ossec-hids-2.9.3/etc/preloaded-vars.conf
- shell: sed -i 's/#USER_ENABLE_ROOTCHECK="y"/USER_ENABLE_ROOTCHECK="y"/' /tmp/ossec-hids-2.9.3/etc/preloaded-vars.conf
- shell: sed -i 's/#USER_ENABLE_EMAIL="y"/USER_ENABLE_EMAIL="n"/' /tmp/ossec-hids-2.9.3/etc/preloaded-vars.conf
- shell: sed -i 's/#USER_ENABLE_FIREWALL_RESPONSE="y"/USER_ENABLE_FIREWALL_RESPONSE="y"/' /tmp/ossec-hids-2.9.3/etc/preloaded-vars.conf
- shell: sed -i 's/#USER_WHITE_LIST="192.168.2.1 192.168.1.0\/24"/USER_WHITE_LIST="10.0.0.0\/8"/' /tmp/ossec-hids-2.9.3/etc/preloaded-vars.conf
- name: install ossec
  shell: /tmp/ossec-hids-2.9.3/install.sh
  register: output
- debug: msg={{ output }}
- name: Change permissions
  shell: setfacl -m "u:svc_ansible.aaam:rwx" /var/ossec/
- shell: setfacl -m "u:svc_ansible.aaam:rwx" /var/ossec/logs
- shell: setfacl -m "u:svc_ansible.aaam:rw-" /var/ossec/logs/active-responses.log
- shell: setfacl -m "u:svc_ansible.aaam:rw-" /var/ossec/logs/ossec.log
- name: Start ossec service
  shell: /var/ossec/bin/ossec-control start
- name: delete the source files
  shell: rm -rf /tmp/ossec-hids-2.9.3
  ignore_errors: yes
- shell: rm -rf /tmp/ossec.2.9.3.tar.gz
  ignore_errors: yes
