apiVersion: kubeadm.k8s.io/v1alpha3
kind: ClusterConfiguration
kubernetesVersion: stable
apiServerCertSANs:
- "{{ lb_name }}"
controlPlaneEndpoint: "{{ lb_ip }}:6443"
etcd:
  external:
    endpoints:
    - https://{{ etcd0 }}:2379
    - https://{{ etcd1 }}:2379
    - https://{{ etcd2 }}:2379
    caFile: /etc/kubernetes/pki/etcd/ca.crt
    certFile: /etc/kubernetes/pki/apiserver-etcd-client.crt
    keyFile: /etc/kubernetes/pki/apiserver-etcd-client.key
networking:
  podSubnet: "{{ pod_cidr }}"
