- name: Install keepalived
  apt: name=keepalived state=latest

- name: keepalived config file
  template: src=../templates/keepalived.conf dest=/etc/keepalived/keepalived.conf

- name: Start and enable the service
  shell: systemctl start keepalived && systemctl enable keepalived

- pause: seconds=30

- name: Install ha proxy load balancer
  apt: name=haproxy state=latest

- name: Copy haproxy config file
  template: src=../templates/haproxy.cfg dest=/etc/haproxy/haproxy.cfg

- name: Start and enable keepalived service
  service: name=haproxy state=restarted enabled=yes

