- name: Get all needed certificates from the local machine
  synchronize: 
    src: /tmp/kube-certs.tgz 
    dest: /root/kube-certs.tgz

- name: Extract certificates archive
  unarchive:
    src: /root/kube-certs.tgz
    dest: /etc/kubernetes
    remote_src: yes

- name: Copy kubeadm config
  template: src=../templates/kubeadm-config.yaml dest=/etc/kubernetes/kubeadm-config.yaml

- name: Join the cluster as master
  shell: kubeadm init --config /etc/kubernetes/kubeadm-config.yaml --ignore-preflight-errors=all

- name: Clean up
  shell: rm /root/kube-certs.tgz -rf && mkdir /root/.kube && cp /etc/kubernetes/admin.conf /root/.kube/config

- name: Wait for masters to be available
  shell: sleep 30

- name: Install pod network weave by default
  shell: kubectl apply -f "https://cloud.weave.works/k8s/net?k8s-version=$(kubectl version | base64 | tr -d '\n')&env.IPALLOC_RANGE={{ pod_cidr }}"
  run_once: true
