### Install all needed requesites
- hosts: all
  become: yes
  remote_user: ansible
  gather_facts: true
  connection: ssh
  roles:
    - prereqs

### Generate etcd certificates
- hosts: etcd-init
  become: yes
  remote_user: ansible
  gather_facts: false
  connection: ssh
  roles:
    - local-certs-gen

### Bootstrap the etcd cluster
- hosts: etcd
  become: yes
  remote_user: ansible
  gather_facts: true
  connection: ssh
  roles:
    - etcd-cluster
     
### Setup haproxy load balancer for masters
- hosts: lb-proxy 
  become: yes
  remote_user: ansible
  gather_facts: false
  connection: ssh
  roles:
    - ha-proxy

### Bootstrap the kube master
- hosts: master-init
  become: yes
  remote_user: ansible
  gather_facts: false
  connection: ssh
  roles:
    - master-bootstrap

### Add other masters
- hosts: masters
  become: yes
  remote_user: ansible
  gather_facts: false
  connection: ssh
  roles:
    - add-masters

### Add workers and pod CNI
- hosts: workers
  become: yes
  remote_user: ansible
  gather_facts: true
  connection: ssh
  roles:
    - add-workers

### Glusterfs storage setup
- hosts: workers
  become: yes
  remote_user: ansible
  gather_facts: true
  connection: ssh
  roles:
    - glusterfs-storage

### Post install tasks
- hosts: master-init
  become: yes
  remote_user: ansible
  connection: ssh
  gather_facts: true
  roles:
    - post-install-tasks
