- name: Add gluster repo
  shell: add-apt-repository ppa:gluster/glusterfs-3.13 -y && apt-get update
- apt: name=glusterfs-server state=latest
- apt: name=glusterfs-client state=latest
- apt: name=thin-provisioning-tools state=latest

- name: Enable and start glusterd service
  service: name=glusterd state=restarted enabled=yes

- name: Add all servers to the pool
  shell: gluster peer probe "{{ item }}"
  with_items:
  - "{{ groups['workers'] }}"
  run_once: true

- name: Check cluster status
  shell: gluster pool list
  register: out
  run_once: true
- debug: msg={{ out }}

- name: Make sure that /root/.ssh exists
  file:
    path: /root/.ssh
    state: directory
    owner: root
    group: root
    mode: 0700
